# Generated by Django 2.0.6 on 2018-06-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(max_length=50)),
                ('status', models.CharField(choices=[('PD', 'Pending'), ('OS', 'Out for Signatures'), ('AC', 'Active'), ('DT', 'Dormant'), ('EX', 'Expired'), ('LD', 'Lead'), ('ST', 'Stale')], default='LD', max_length=2)),
                ('new_renew', models.CharField(choices=[('N', 'New'), ('R', 'Renew')], default='N', max_length=1)),
                ('hubspot', models.URLField()),
                ('annual_fee', models.CharField(max_length=50)),
                ('paid_in_full', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('agreement', models.URLField()),
                ('invoice_request', models.CharField(choices=[('PAID', 'Paid'), ('SENT', 'Sent'), ('REQUESTED', 'Requested'), ('NOT READY', 'Not Ready to Request'), ('NUMFOCUS', 'Request from NumFOCUS')], max_length=18)),
                ('event_status', models.CharField(choices=[('COMPLETE', 'Complete'), ('SCHEDULED', 'Scheduled'), ('PENDING', 'Pending')], default='PENDING', max_length=9)),
                ('event', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SS', 'Standard Silver'), ('CS', 'Corporate Silver'), ('SG', 'Standard Gold'), ('SP', 'Standard Platinum'), ('CP', 'Coordinated Platinum'), ('SW', 'SWC Contract'), ('DC', 'DC Contract'), ('CT', 'Contract')], default='CT', max_length=2)),
                ('num_org_workshop', models.SmallIntegerField()),
                ('instrucutor', models.SmallIntegerField()),
                ('reserve', models.BooleanField()),
                ('inh_trainer', models.BooleanField()),
                ('loc_train', models.BooleanField()),
                ('publicize', models.BooleanField()),
                ('recruit', models.BooleanField()),
                ('coordinate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=2)),
                ('has_active', models.BooleanField()),
                ('domain', models.URLField()),
                ('umbrella', models.BooleanField()),
                ('vendor_reg', models.BooleanField()),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='membership.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('advisory_council', models.BooleanField()),
                ('signatory', models.BooleanField()),
                ('member_contact', models.BooleanField()),
                ('billing_contact', models.BooleanField()),
                ('trainer', models.BooleanField()),
                ('merger_notify', models.BooleanField()),
                ('nf2nci_letter', models.BooleanField()),
                ('hubspot', models.URLField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='member_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.MembershipTerms'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.Organization'),
        ),
    ]
