# Generated by Django 2.0.6 on 2018-06-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='surname',
            new_name='last_name',
        ),
    ]
