# Generated by Django 2.0.6 on 2018-08-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='umbrella',
            field=models.BooleanField(help_text='Does this membership cover other organizations under                   its “umbrella”?', verbose_name='Is umbrella?'),
        ),
        migrations.AlterField(
            model_name='term',
            name='coordinate',
            field=models.BooleanField(help_text='Do they have a workshop coordinator offered up                   as in-kind effort?', verbose_name='Offered coordinator?'),
        ),
    ]
