# Generated by Django 2.0.6 on 2018-06-12 20:58

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('membership', '0003_auto_20180612_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembershipTerms',
            new_name='MembershipTerm',
        ),
    ]
