# Generated by Django 2.0.6 on 2018-06-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('membership', '0005_auto_20180613_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Note', max_length=64, verbose_name='Note title')),
                ('content', models.TextField(help_text='Content of the Note', max_length=512, verbose_name='Note content')),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Time of the last update of the note', verbose_name='Note time')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
