# Generated by Django 2.0.6 on 2018-06-13 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='time',
        ),
        migrations.AddField(
            model_name='note',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date and time of the last update of the note', verbose_name='Note time'),
        ),
    ]
