# Generated by Django 2.0.6 on 2018-06-18 16:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('membership', '0007_auto_20180613_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembershipTerm',
            new_name='Term',
        ),
    ]
