# Generated by Django 2.0.6 on 2018-06-18 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20180618_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Contact',
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ForeignKey(blank=True, help_text='The names of those members if umbrella', null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Organization'),
        ),
    ]
