# Generated by Django 2.0.6 on 2018-06-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20180618_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='loc_train',
            new_name='local_train',
        ),
    ]
