# Generated by Django 2.0.6 on 2018-06-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20180619_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='mem_type',
            field=models.CharField(choices=[('SS', 'Standard Silver'), ('CS', 'Corporate Silver'), ('SG', 'Standard Gold'), ('SP', 'Standard Platinum'), ('CP', 'Coordinate Platinum'), ('IT', 'Instructor Training'), ('SC', 'SWC Contract'), ('DC', 'DC Contract'), ('CT', 'Contract')], default='CT', help_text='Descriptive name for membership', max_length=2, unique=True, verbose_name='Membership type'),
        ),
    ]
